### PR TITLE
Add support for Glide

### PR DESCRIPTION
**Pull request by pavlospt**

### CODE REVIEW

**Comment by Rainer-Lang** [comment]
Is it possible to merge this PR?

**Comment by radzio** [comment]
Duplicate of https://github.com/TangoAgency/avatar-view/pull/4

**Comment by pavlospt** [comment]
@radzio I had created the first PR adding such functionality. And then the other PR occurred, so can you tell me how this is a duplicate? I had also commented on the PR that you merged

**Comment by radzio** [comment]
@pavlospt  These two PRs were almost the same so one of them was a duplicate for me. I've merged the first one. Your changes (thanks again!) were already deployed to jcenter in version 0.0.2

**Comment by pavlospt** [comment]
Ok!

**Review by Meinne1 — COMMENTED** [review]
Mh

**Pull request closed without merging**
